### ISSUE TITLE
Change latest trade detail ws event interface

### ISSUE THREAD

**Issue by singlesly** [singlesly/bingx-api#38]
**Price**: 5$

got message as fact is
```json
{
      "code":0,
      "dataType":"BTC-USDT@trade",
      "data":[
         {
            "q":"0.1783",
            "p":"26615.4",
            "T":1697132867944,
            "m":true,
            "s":"BTC-USDT"
         }
      ]
   }
```

**Comment by aliraza556** [comment]
@singlesly task available?

**Comment by singlesly** [comment]
> @singlesly task available?

Yes

**Comment by aliraza556** [comment]
Hi @singlesly,
Please mention the code file.

**Comment by singlesly** [comment]
https://github.com/singlesly/bingx-api/blob/3f3e1346ed36896dfded9eb147a1997433c7083c/src/bingx-socket/events/marker-websocket-events.ts#L27

Looks like this interface all props except `dataType` must be into sub field `data` which must be array of objects with fields

**Comment by singlesly** [comment]
and rename file in word `marker` misstake must be `market`

**Comment by aliraza556** [comment]
@singlesly,
check this:
export interface LatestTradeEvent extends MarkerWebsocketEvents {
  dataType: TradeDataType;
  data: Array<{
    T: TransactionTimeInMillis;
    s: TradingPair;
    m: IsMarketMaker;
    p: Price;
  }>;
}

**Comment by aliraza556** [comment]
Please give bingx api.

**Comment by aliraza556** [comment]
Ok i try

**Comment by aliraza556** [comment]
Hi @singlesly,
Please see [demo](https://www.loom.com/share/fb28d7e247e94cd3b48c66c068a2b278).

**Comment by singlesly** [comment]
yes. ok

**Comment by singlesly** [comment]
create merge request

**Comment by aliraza556** [comment]
@singlesly, I cannot clone the project. I'm just testing on my side. If I paste the full code, it's fine.

**Comment by aliraza556** [comment]
@singlesly,
Ok, I clone the project then I create a pull request.

**Comment by singlesly** [comment]
ye just change interface only

**Comment by aliraza556** [comment]
> ye just change interface only

just give me 2 mint i make a PR

**Comment by aliraza556** [comment]
Hi @singlesly,
Please check this PR #62
