### ISSUE TITLE
implement user history orders

### ISSUE THREAD

**Issue by singlesly** [singlesly/bingx-api#63]
https://bingx-api.github.io/docs/#/en-us/swapV2/trade-api.html#User's%20History%20Orders

price: 10$

**Comment by aliraza556** [comment]
@singlesly available?

**Comment by singlesly** [comment]
No. Implemented Already. Do u need tickets?

**Comment by aliraza556** [comment]
Yes

**Comment by aliraza556** [comment]
> No. Implemented Already. Do u need tickets?

Yes, I need new tickets.
